version: "3"

services:
  spring:
    container_name: spring
    build: ./backend/notify
    ports:
      - "9998:9998"
    volumes:
      - /spring:/image
    restart: on-failure

  # react:
  #   container_name: react
  #   build: ./frontend/overmountain
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /react:/image
  #   restart: on-failure
