version: "3.7"

services:
  spring-eureka:
    container_name: spring-eureka
    build: ./eureka
    ports:
      - "9001:9001"
    volumes:
      - /eureka:/eureka
    restart: on-failure
  spring-gateway:
    container_name: spring-gateway
    build: ./gateway
    ports:
      - "9000:9000"
    volumes:
      - /gateway:/gateway
    restart: on-failure
