
server:
  port: 8081

spring:
  application:
    name: core

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://dodamdodam.site:8761/eureka

